### ISSUE TITLE
Generated Fakes look different with implementation of Repurposing GANs

### ISSUE THREAD

**Issue by MationPlays** [bryandlee/repurpose_gan#11]
Hello,
I trained a stylegan2-ada-pytorch model(https://github.com/NVlabs/stylegan2-ada-pytorch), I used resume pretrained with car images(config f, https://github.com/justinpinkney/awesome-pretrained-stylegan2) and trained the pretrained stylegan with more car images, but just for 200kimg.
Here is an example of a generated sample in the fakes grid:

![This is an image](https://github.com/MationPlays/images/blob/main/fakeimage.PNG?raw=true)
I converted the .pkl network checkpoint to .pt with the export_weights.py from here: https://github.com/dvschultz/stylegan2-ada-pytorch.git
When I use the few shot segmentation notebook the generated fake looks like this:

![This is an image](https://github.com/MationPlays/images/blob/main/sampleimage.PNG?raw=true)

I have no idea why it looks like this. I thought it should look similar to the fakes on the fakes grid of the training. Is the generator not trained enough, it almost looks like edge detection image? Or is this possibly a conversion problem?
Any help would be appreciated!

**Comment by bryandlee** [comment]
Hi, it seems like a conversion issue. Have you checked the [conversion result](https://github.com/dvschultz/stylegan2-ada-pytorch/blob/main/SG2_ADA_PT_to_Rosinality.ipynb)?

**Comment by MationPlays** [comment]
> Hi, it seems like a conversion issue. Have you checked the [conversion result](https://github.com/dvschultz/stylegan2-ada-pytorch/blob/main/SG2_ADA_PT_to_Rosinality.ipynb)?

Thank you for the quick reply, I wasn't aware of that notebook. I tested it, but I get errors:

RuntimeError: Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "style.3.weight", "style.3.bias", "style.4.weight", "style.4.bias", "style.5.weight", "style.5.bias", "style.6.weight", "style.6.bias", "style.7.weight", "style.7.bias", "style.8.weight", "style.8.bias". 
	size mismatch for convs.6.conv.weight: copying a param with shape torch.Size([1, 512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([1, 256, 512, 3, 3]).
	size mismatch for convs.6.activate.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for convs.7.conv.weight: copying a param with shape torch.Size([1, 512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([1, 256, 256, 3, 3]).
	size mismatch for convs.7.conv.modulation.weight: copying a param with shape torch.Size([512, 512]) from checkpoint, the shape in current model is torch.Size([256, 512]).
	size mismatch for convs.7.conv.modulatio....

I read it is because I used auto config, but did not test it yet

**Comment by MationPlays** [comment]
Ok I found the mistake it was just the wrong image size set in the code
image_size = 256 instead of 512
sorry I did not see that
