### ISSUE TITLE
CUDA out of Memory when loading one sample

### ISSUE THREAD

**Issue by MationPlays** [bryandlee/repurpose_gan#14]
Hello, 
I hope anybody can help me, I am kind of frustrated.
I always get the this error when training with GPU:
'RuntimeError: CUDA out of memory. Tried to allocate 5.38 GiB (GPU 0; 11.17 GiB total capacity; 5.76 GiB already allocated; 4.71 GiB free; 5.84 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF'
I only load one sample. I thought it has to do with the concat_features method where the 5504 channels get created to match the in_ch(input channel i suppose). I also train with significantly more classes(70), but I tried it with only defining 2 and still got this error.
Please help anyone, any help is appreciated. Thanks

**Comment by MationPlays** [comment]
Also I work with databricks, nvidia-smi does not work there

**Comment by numb89757** [comment]
I just want to implement the code, but the example program take my disk over 50GB (virtual memory). Failed to run in my poor laptop :(
Maybe the model need lots of memory to run?

**Comment by MationPlays** [comment]
I now know it did not work, one sample had 5504 channels in one dimension, that are the concatenated feature outputs of all layers. I used a higher resolution 512 instead of 256 so it the loaded sample was bigger by a big factor so it did not fit on the memory. The programm needs an incredible amount of memory to run
