### ISSUE TITLE
Can you use any StyleGAN 2 ADA Generator?

### ISSUE THREAD

**Issue by MationPlays** [bryandlee/repurpose_gan#8]
Hey,
I want to use the styleGAN2 ADA Pytorch to train with unlabeled data of cars. I want to use the stylegan2 ada pytorch from this Video:
https://www.youtube.com/watch?v=BCde68k6KXg&t=0s&ab_channel=JeffHeaton
Can there be compatibility problems with Generators from other stylegan versions or is there no difference?
I am kind of new to stylegan.
Thanks

**Comment by bryandlee** [comment]
This repo uses [rosinality's implementation of stylegan2](https://github.com/rosinality/stylegan2-pytorch). 

The one you mentioned is an official Nvidia version, and I believe you can convert the model weights: https://github.com/rosinality/stylegan2-pytorch/issues/206

**Comment by MationPlays** [comment]
> This repo uses [rosinality's implementation of stylegan2](https://github.com/rosinality/stylegan2-pytorch).
> 
> The one you mentioned is an official Nvidia version, and I believe you can convert the model weights: [rosinality/stylegan2-pytorch#206](https://github.com/rosinality/stylegan2-pytorch/issues/206)

Thanks for the reply but I rather stick with the rosinality one so I hope there won't be much problems
